### ISSUE TITLE
Issues with es6 modules in Jest

### ISSUE THREAD

**Issue by alanrubin** [jonbnewman/mobx-store-provider#1]
Thanks for this nice library and the effort spent creating it.

Just to let you know I had issues with ES6 and Jest, it seems your library is not transformed into ES5 when publishing, is that the case or I missing something? So when trying to run a test in Jest (using default create-react-app configuration), I get the following error:

```bash
 PASS  src/atoms/Clock/Clock.test.tsx
 FAIL  src/organisms/Header/Header.test.tsx
  ● Test suite failed to run

    /Users/alanrubin/Keytree/Sense/matrix-sense-signage-ui/node_modules/mobx-store-provider/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import useProvider from "./hooks/useProvider";
                                                                                                    ^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      3 | import Clock from 'atoms/Clock'
      4 | import { observer } from 'mobx-react'
    > 5 | import { useStore } from 'mobx-store-provider'
        | ^
      6 | import { IAppStore } from 'models/AppStore'
      7 | import MatrixLogo from './matrix-logo.svg'
```

That seems to be caused because jest doesn't transpile the node_modules dir - I solved by adding to the package.json a jest configuration to transpile your library in node_modules:

```json
"jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!mobx-store-provider)/"
    ]
  }
```

But isn't it better to have the library published transpiled?

Thanks,
Alan

**Comment by jonbnewman** [comment]
First, thanks for reporting this, and thanks for the compliment.

Currently the output target is `ESNext`, as that created the smallest output, while still compatible with how I was importing.

That said, to be more compatible with others using the library...it definitely would probably help for it to spit out a more standard ES5 format.

I am at the office right now, but I will push an update for this later tonight. There are some minor type updates I have to push as well.

Again, thanks for reporting this.

**Comment by jonbnewman** [comment]
Just pushed `1.4.1` which is exporting with a CommonJS format now.

Let me know if this solves you issue and I will close the ticket...again, thanks for letting me know.

**Comment by alanrubin** [comment]
Just tested it, the change fixed the issue, thanks for the quick reply.
