### ISSUE TITLE
Suggestion: rename createStore to useCreateStore

### ISSUE THREAD

**Issue by JulioC** [jonbnewman/mobx-store-provider#3]
When first looking at code using this library, it's hard to guess that `createStore` is a hook.

I believe following the pattern of prefixing it with `use` would better describe it.

This change would require a breaking update, but it can be preceded by a deprecation period, updating the docs to favor the new method.

**Comment by jonbnewman** [comment]
After having thought about this, I generally agree...I am working on this.

**Comment by jonbnewman** [comment]
This is address in the latest release, `v1.5.0`.
