### ISSUE TITLE
Suggestion: mapStateToProps name is misleading

### ISSUE THREAD

**Issue by JulioC** [jonbnewman/mobx-store-provider#4]
The `mapStateToProps` parameter in `useStore(identifier, mapStateToProps)` is used to map a store to a "view" of it, there are no props on that. I understand the name was taken from redux inject, where it does make sense, but I don't think that's the case in this library

I believe it would be more suitable to call it `mapStore` or something along that.

**Comment by jonbnewman** [comment]
Another good suggestion...I had thought the naming here could be improved for a while now as well. Indeed I sort of just stole the `mapStateToProps` nomenclature from redux...and it is not totally applicable here (seeing as it is mapping the store...and not props).

I am working on this as well.

**Comment by jonbnewman** [comment]
This is address in the latest release, `v1.5.0`.
