### ISSUE TITLE
Store gets recreated everytime component is re-rendered

### ISSUE THREAD

**Issue by JulioC** [jonbnewman/mobx-store-provider#6]
When using useCreateStore, the factory method gets called whenever the host component is re-rendered.

I believe this is not the expected behavior, but some code might be relying on this.

This happens because it's called on the hook body:

```typescript
function useCreateStore(factory: Factory): any {
  return useRef(factory()).current;
}
```

My suggestion is to replace this call with a memo-d value:

```typescript
function useCreateStore(factory: Factory, deps: any = []) : any {
  return useMemo(factory, deps);
}
```

**Comment by JulioC** [comment]
My current workaround

```javascript
const App = () => {
  const store = React.useMemo(
    () =>AppStore.create(),
    []
  );
  const appStore = createStore(() => store);
  // ..

}

```

**Comment by jonbnewman** [comment]
Thanks for reporting this!

I have now memoized the useCreateStore/createStore logic in the latest release `1.5.1`, let me know if you still have issues after updating.
