### ISSUE TITLE
next.js compatibility?

### ISSUE THREAD

**Issue by kevinsproles** [jonbnewman/mobx-store-provider#8]
As I see you've taken the lead with functional components and useContext per https://github.com/mobxjs/mobx-state-tree/issues/1363#issuecomment-578452511

I'd like to use your lib with next.js, wondering if it would work.

The MST example vercel has is from a few years back and uses obsolete patterns (class components and injection) https://github.com/vercel/next.js/tree/canary/examples/with-mobx-state-tree-typescript

**Comment by jonbnewman** [comment]
It should work fine, however I have not tried it specifically with next.js. I do have a project at work which uses Gatsby which is also rendered server side and it works fine with mobx-store-provider.

There really isn't anything special about mobx-store-provider...it uses React Context...so as long as next.js allows standard React Context (which I am sure it does) then it should work out of the box.

Let me know if you have any issues.

**Comment by kevinsproles** [comment]
@jonbnewman Not sure, just submitted a PR to vercel/next.js MST example to use React hooks.

But got hung up on the `useContext` piece, maybe could use your eyes on this: https://github.com/vercel/next.js/pull/15237#discussion_r456075013

**Comment by jonbnewman** [comment]
@kevinsproles well your link doesn't show any mobx-store-provider use....but from the snipped there I can't tell if you've Provided the component with the instance correctly. Have you tried slipping mobx-store-provider in there (at least temporarily) to rule out improper context usage?

If possible, can you post a complete jsfiddle or something that shows the issue you are facing? Or maybe create a branch off your fork of next.js with the complete non-working context example you were having issues with?

**Comment by jonbnewman** [comment]
Closing this, as it's not really a mobx-store-provider question ...and I also haven't heard back in over a week.

Let me know if you end up posting a more complete example showing your issues - and I will take a look.
